import { serve } from 'https://deno.land/std@0.177.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: CORS });

  try {
    const {
      email,
      password,
      full_name,
      phone,
      omang_number,
      date_of_birth,
      gender,
      district,
      village,
    } = await req.json();

    // Validate required fields
    if (!email || !password || !full_name || !omang_number || !district) {
      return new Response(
        JSON.stringify({ error: 'Missing required fields: email, password, full_name, omang_number, district' }),
        { status: 400, headers: { ...CORS, 'Content-Type': 'application/json' } }
      );
    }

    // Validate Omang format (7 digits, Botswana national ID)
    if (!/^\d{7,9}$/.test(omang_number.trim())) {
      return new Response(
        JSON.stringify({ error: 'Omang number must be 7–9 digits.' }),
        { status: 400, headers: { ...CORS, 'Content-Type': 'application/json' } }
      );
    }

    // Admin client (service role) for privileged operations
    const adminClient = createClient(
      Deno.env.get('SUPABASE_URL')!,
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,
      { auth: { autoRefreshToken: false, persistSession: false } }
    );

    // 1. Check omang uniqueness before creating auth user
    const { data: existingFarmer } = await adminClient
      .from('farmers')
      .select('id')
      .eq('omang_number', omang_number.trim())
      .maybeSingle();

    if (existingFarmer) {
      return new Response(
        JSON.stringify({ error: 'An account with this Omang number already exists.' }),
        { status: 409, headers: { ...CORS, 'Content-Type': 'application/json' } }
      );
    }

    // 2. Create auth user (triggers handle_new_user → inserts base profiles row)
    const { data: authData, error: authErr } = await adminClient.auth.admin.createUser({
      email,
      password,
      email_confirm: true, // skip email verification for self-registration
      user_metadata: { full_name },
    });

    if (authErr || !authData.user) {
      return new Response(
        JSON.stringify({ error: authErr?.message ?? 'Failed to create account' }),
        { status: 400, headers: { ...CORS, 'Content-Type': 'application/json' } }
      );
    }

    const userId = authData.user.id;

    // 3. Update profiles row with all collected fields + set role = 'farmer'
    const { error: profileErr } = await adminClient
      .from('profiles')
      .update({
        full_name,
        phone: phone || null,
        district,
        village: village || null,
        role: 'farmer',
        status: 'pending_verification',
      })
      .eq('id', userId);

    if (profileErr) {
      // Rollback: delete auth user
      await adminClient.auth.admin.deleteUser(userId);
      return new Response(
        JSON.stringify({ error: 'Profile setup failed: ' + profileErr.message }),
        { status: 500, headers: { ...CORS, 'Content-Type': 'application/json' } }
      );
    }

    // 4. Insert farmers record (omang, dob, gender — farmer_code auto-generated by trigger)
    const { error: farmerErr } = await adminClient
      .from('farmers')
      .insert({
        profile_id: userId,
        omang_number: omang_number.trim(),
        date_of_birth: date_of_birth || null,
        gender: gender || null,
      });

    if (farmerErr) {
      // Rollback: delete auth user (cascades profiles)
      await adminClient.auth.admin.deleteUser(userId);
      return new Response(
        JSON.stringify({ error: 'Farmer record setup failed: ' + farmerErr.message }),
        { status: 500, headers: { ...CORS, 'Content-Type': 'application/json' } }
      );
    }

    // 5. Sign in with anon client to return a usable session token
    const anonClient = createClient(
      Deno.env.get('SUPABASE_URL')!,
      Deno.env.get('SUPABASE_ANON_KEY')!
    );
    const { data: signInData, error: signInErr } = await anonClient.auth.signInWithPassword({
      email,
      password,
    });

    if (signInErr || !signInData.session) {
      // Account created but sign-in failed — user can log in manually
      return new Response(
        JSON.stringify({ success: true, session: null, message: 'Account created. Please log in.' }),
        { status: 201, headers: { ...CORS, 'Content-Type': 'application/json' } }
      );
    }

    return new Response(
      JSON.stringify({ success: true, session: signInData.session }),
      { status: 201, headers: { ...CORS, 'Content-Type': 'application/json' } }
    );
  } catch (err: any) {
    return new Response(
      JSON.stringify({ error: err.message ?? 'Internal server error' }),
      { status: 500, headers: { ...CORS, 'Content-Type': 'application/json' } }
    );
  }
});
